module.exports = [
  "I'm sensing a lot of uncertainty around your question.",
  "The spirits are not providing a clear answer at this time.",
  "I'm sorry, the cosmic energies are in flux, and I can't provide a definitive response.",
  "Sometimes, the universe keeps its secrets hidden.",
  "It's as if a shroud of mystery surrounds your inquiry.",
  "I sense a veil of uncertainty that prevents me from answering.",
  "The future is not yet set in stone, and it's unclear at the moment.",
  "I'm receiving mixed signals, making it difficult to provide a clear answer.",
  "The answer you seek is elusive, like a whisper in the wind.",
  "The cosmic vibrations are complex, and I cannot decipher them right now.",
  "I'm afraid I can't see a clear path to an answer at this time.",
  "The energies are too chaotic for me to provide a definite response.",
  "I sense a cloud of confusion around your question.",
  "The universe is keeping its secrets locked away for now.",
  "I cannot discern a clear answer in the current cosmic alignment.",
  "Sometimes, the answers are meant to reveal themselves in time.",
  "It's as if the universe is withholding its wisdom from us today.",
  "I'm sorry, but the answer eludes me at this moment.",
  "I sense a puzzle, and the pieces are not yet in place for me to answer.",
  "The enigma of your question leaves me without a response.",
];
